name: mrhisum
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - cudatoolkit=11.0        # GPU support for PyTorch on Windows
  - numpy
  - tqdm
  - pandas
  - scipy
  - h5py=2.10.0
  - scikit-learn
  - pytorch=1.7.1
  - torchvision=0.8.2
  - einops=0.6.1
  - torchaudio=0.7.2
  - tensorflow=2.3.0
  - tensorboard=2.4.1
  - tensorflow-estimator=2.6.0
  - keras-preprocessing=1.1.2
  - jupyterlab               # interactive notebooks
  - ipykernel                # kernel for Jupyter
  - pip:
      - ortools==9.5.2237    # your one custom pip package
